/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimaryRouteImport } from './routes/primary'
import { Route as JuniorSecondaryRouteImport } from './routes/junior-secondary'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PrimaryRoute = PrimaryRouteImport.update({
  id: '/primary',
  path: '/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorSecondaryRoute = JuniorSecondaryRouteImport.update({
  id: '/junior-secondary',
  path: '/junior-secondary',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/junior-secondary': typeof JuniorSecondaryRoute
  '/primary': typeof PrimaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/junior-secondary': typeof JuniorSecondaryRoute
  '/primary': typeof PrimaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/junior-secondary': typeof JuniorSecondaryRoute
  '/primary': typeof PrimaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/clubs'
    | '/contact'
    | '/founder'
    | '/junior-secondary'
    | '/primary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/clubs'
    | '/contact'
    | '/founder'
    | '/junior-secondary'
    | '/primary'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/clubs'
    | '/contact'
    | '/founder'
    | '/junior-secondary'
    | '/primary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ClubsRoute: typeof ClubsRoute
  ContactRoute: typeof ContactRoute
  FounderRoute: typeof FounderRoute
  JuniorSecondaryRoute: typeof JuniorSecondaryRoute
  PrimaryRoute: typeof PrimaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primary': {
      id: '/primary'
      path: '/primary'
      fullPath: '/primary'
      preLoaderRoute: typeof PrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junior-secondary': {
      id: '/junior-secondary'
      path: '/junior-secondary'
      fullPath: '/junior-secondary'
      preLoaderRoute: typeof JuniorSecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  ClubsRoute: ClubsRoute,
  ContactRoute: ContactRoute,
  FounderRoute: FounderRoute,
  JuniorSecondaryRoute: JuniorSecondaryRoute,
  PrimaryRoute: PrimaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
